In [34]:
import cv2
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
training_files = list(Path("./train").glob("*"))

labels = [file.as_posix().split("/")[1].split(".")[0] for file in training_files]

In [36]:
train = pd.DataFrame({'path': training_files, 'label': labels})

In [38]:
testing_files = list(Path("./test").glob("*"))

In [39]:
test = pd.DataFrame({'test': testing_files, 'label': 0})

In [37]:
train

                     path label
0         train\cat.0.jpg   cat
1         train\cat.1.jpg   cat
2        train\cat.10.jpg   cat
3       train\cat.100.jpg   cat
4      train\cat.1000.jpg   cat
...                   ...   ...
24995  train\dog.9995.jpg   dog
24996  train\dog.9996.jpg   dog
24997  train\dog.9997.jpg   dog
24998  train\dog.9998.jpg   dog
24999  train\dog.9999.jpg   dog

[25000 rows x 2 columns]

In [40]:
test

                 test  label
0          test\1.jpg      0
1         test\10.jpg      0
2        test\100.jpg      0
3       test\1000.jpg      0
4      test\10000.jpg      0
...               ...    ...
12495   test\9995.jpg      0
12496   test\9996.jpg      0
12497   test\9997.jpg      0
12498   test\9998.jpg      0
12499   test\9999.jpg      0

[12500 rows x 2 columns]